# This is a basic workflow to help you get started with Actions

name: Testing

on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: version
        uses: arslnmsd/kubectl@v1.17.9
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        with:
          args: version

      - name: get pods
        uses: arslnmsd/kubectl@v1.17.9
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        with:
          args: get pods -n qa

      - name: config get contexts
        uses: arslnmsd/kubectl@v1.17.9
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        with:
          args: config get-contexts      
